### ISSUE TITLE
Python 3.6 + OS X needs python.app

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/ipython-feedstock#20]
`defaults` does not provide, at least at the moment, a `python.app` package for Python 3.6.

**Comment by minrk** [comment]
Why does it need python.app? I see it in the dependency, but don't understand what it would be used for in IPython.

**Comment by ocefpaf** [comment]
I don't  known, not a Mac user, this was introduced in https://github.com/conda-forge/ipython-feedstock/pull/8

@mwcraig is this still needed?

**Comment by minrk** [comment]
From the discussion in #8, it appears to be caused by a bug in conda < 4.1, where entrypoints get mangled to call python.app. If that's true, then *every* package that has any entrypoint should have the same requirement. I don't think this is done in [other packages](https://github.com/conda-forge/cython-feedstock/blob/master/recipe/meta.yaml), so we probably shouldn't do it in IPython.

**Comment by minrk** [comment]
#21 removes the python.app dependency

**Comment by mwcraig** [comment]
Just checked, and `python.app` is no longer a dependency for defaults ipython, so I agree we should remove it here too.
